---

- hosts: servers
  tags: ['never', 'prepare']
  roles:
  - provider/bare/prepare

- hosts: servers
  vars:
    instance_name: DevStack
    cpu: 4
    mem: 4096
  roles:
  - provider/bare/boot

- hosts: machines
  tags: ['never', 'install']
  roles:
  - devstack
