---

- hosts: servers
  tags: ['never', 'prepare']
  roles:
  - provider/bare/prepare

- hosts: servers
  vars:
    instance_name: OpenStackHelm
    cpu: 8
    mem: 16384
    size: 50
  roles:
  - provider/bare/boot

- hosts: machines
  tags: ['never', 'install']
  roles:
  - openstack
