- name: Delete existing DNS entry
  cloudflare_dns:
    zone: "{{ zone_name }}"
    record: "{{ record_name }}"
    type: A
    state: absent
    account_email: "{{ cloudflare_email }}"
    account_api_token: "{{ cloudflare_api_token }}"

- name: Add new DNS entry with instance IP
  cloudflare_dns:
    zone: "{{ zone_name }}"
    record: "{{ record_name }}"
    type: A
    value: "{{ ansible_host }}"
    proxied: no
    account_email: "{{ cloudflare_email }}"
    account_api_token: "{{ cloudflare_api_token }}"
