- name: Update packages list and upgrade if needed
  apt:
    update_cache: true
    upgrade: true
  become: yes

- name: Install packages
  apt:
    name: "{{ packages }}"
  become: yes

- name: Add stack user
  user:
    name: stack
    shell: /bin/bash
    home: /opt/stack
  become: yes

- name: Add stack user as sudoer
  copy:
    src: stack
    dest: /etc/sudoers.d/stack
  become: yes

- name: Download repositories
  git:
    repo: "https://opendev.org/{{ item }}"
    dest: "~/{{ item.split('/')[1] }}"
    clone: yes
    force: yes
  become: true
  become_user: stack
  with_items:
    - openstack-dev/devstack
    - openstack/kuryr-kubernetes

- name: Create local pip config
  file:
    path: "~/.config/pip/"
    state: directory
  become: true
  become_user: stack

- name: Setup pip
  copy:
    src: pip.conf
    dest: "~/.config/pip/pip.conf"
  become: true
  become_user: stack

- name: Setup DevStack
  copy:
    src: local.conf
    dest: "~/devstack/local.conf"
  become: true
  become_user: stack
