- name: Update packages list
  apt:
    update_cache: yes
    upgrade: yes
  become: yes

- name: Install packages
  apt:
    name: "{{ packages }}"
  become: yes

- name: Install python packages
  pip:
    name: "{{ pip_packages }}"
    executable: pip
  become: yes

- name: Add Docker GPG public key
  shell: |
    curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo ${ID})/gpg | sudo apt-key add -
  args:
    warn: false

- name: Add Docker APT repository url
  shell: |
    source /etc/os-release
    sudo add-apt-repository \
       "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo ${ID}) \
       $(lsb_release -cs) \
       stable"

- name: Install Docker CE
  apt:
    name: docker-ce
    update_cache: yes
  become: yes

- name: Check Docker service
  service:
    name: docker
    state: restarted
  become: yes
